---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - name: server
        image: muralidharanm/murallidharanmrepo:checkoutservice
        ports:
        - containerPort: 5050
        env:
        - name: PORT
          value: "5050"
        - name: productcatalogservice
          value: "10.110.127.203"
        - name: shippingservice
          value: "10.107.169.49"
        - name: paymentservice
          value: "10.105.30.230"
        - name: emailservice
          value: "10.100.220.103"
        - name: currencyservice
          value: "10.106.83.228"
        - name: cartservice
          value: "10.104.192.120 "
      imagePullSecrets:
      - name: container-migration
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
  - name: grpc
    port: 5050
    targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
spec:
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
      - name: server
        image: muralidharanm/murallidharanmrepo:recommendationservice
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: productcatalogservice
          value: "10.110.127.203"
        - name: DISABLE_PROFILER
          value: "1"
      imagePullSecrets:
      - name: container-migration
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
spec:
  type: ClusterIP
  selector:
    app: recommendationservice
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: server
        image: muralidharanm/murallidharanmrepo:latfrontend
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
         - name: productcatalogservice
          value: "10.110.127.203"
        - name: currencyservice
          value: "10.106.83.228"
        - name: cartservice
          value: "10.104.192.120"
        - name: recommendationservice
          value: "10.98.200.187"
        - name: shippingservice
          value: "10.107.169.49"
        - name: checkoutservice
          value: "10.106.171.109"
        - name: adservice
          value: "10.106.223.136"
        
        - name: ENABLE_PROFILER
          value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: grpc
    port: 80
    targetPort: 8080
