apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: server
        image: muralidharanm/murallidharanmrepo:emailservice
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_PROFILER
          value: "1"
      imagePullSecrets:
      - name: container-migration
---
apiVersion: v1
kind: Service
metadata:
  name: email-headless
spec:
  type: Headless
  selector:
    app: email
  ports:
  - port: 5000
    targetPort: 8080
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - name: server
        image: muralidharanm/murallidharanmrepo:checkoutservice
        ports:
        - containerPort: 5050
        env:
        - name: PORT
          value: "5050"
        - name: PRODUCT_CATALOG_SERVICE
          value: http://productcatalog-headless.default.svc.cluster.local
        - name: SHIPPING_SERVICE
          value: http://shipping-headless.default.svc.cluster.local
        - name: PAYMENT_SERVICE
          value: http://payment-headless.default.svc.cluster.local 
        - name: EMAIL_SERVICE
          value: http://email-headless.default.svc.cluster.local
        - name: CURRENCY_SERVICE
          value: http://currency-headless.default.svc.cluster.local 
        - name: CART_SERVICE
          value: http://cart-headless.default.svc.cluster.local
      imagePullSecrets:
      - name: container-migration
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-headless
spec:
  type: Headless
  selector:
    app: email
  ports:
  - port: 5050
    targetPort: 5050
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
spec:
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
      - name: server
        image: muralidharanm/murallidharanmrepo:recommendationservice
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE
          value: http://productcatalog-headless.default.svc.cluster.local
        - name: DISABLE_PROFILER
          value: "1"
      imagePullSecrets:
      - name: container-migration
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-headless
spec:
  type: Headless
  selector:
    app: recommendation
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: server
        image: muralidharanm/murallidharanmrepo:frontend1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: RECOMMENDATION_SERVICE_ADDR
          value:http://recommendation-headless.default.svc.cluster.local
        - name: CHECKOUT_SERVICE_ADDR
          value:http://checkout-headless.default.svc.cluster.local
        - name: AD_SERVICE
          value: http://ad-headless.default.svc.cluster.local
        - name: PRODUCT_CATALOG_SERVICE
          value: http://productcatalog-headless.default.svc.cluster.local
        - name: SHIPPING_SERVICE
          value: http://shipping-headless.default.svc.cluster.local
        - name: PAYMENT_SERVICE
          value: http://payment-headless.default.svc.cluster.local 
        - name: EMAIL_SERVICE
          value: http://email-headless.default.svc.cluster.local
        - name: CURRENCY_SERVICE
          value: http://currency-headless.default.svc.cluster.local 
        - name: CART_SERVICE
          value: http://cart-headless.default.svc.cluster.local
        - name: ENV_PLATFORM
          value: "aws"
        - name: ENABLE_PROFILER
          value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: grpc
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: muralidharanm/murallidharanmrepo:paymentservice
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-headless
spec:
  type: Headless
  selector:
    app: payment
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
      - name: server
        image: muralidharanm/murallidharanmrepo:productcatalogservice
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
        - name: DISABLE_PROFILER
          value: "1"
   
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalog-headless
spec:
  type: Headless
  selector:
    app: productcatalog
  ports:
  - port: 3550
    targetPort: 3550
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - name: server
        image: muralidharanm/murallidharanmrepo:cartservice
        ports:
        - containerPort: 7070
        env:
        - name: REDIS
          value: http://redis-headless.default.svc.cluster.local

---
apiVersion: v1
kind: Service
metadata:
  name: cart-headless
spec:
  type: Headless
  selector:
    app: cart
  ports:
  - port: 7070
    targetPort: 7070
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      initContainers:
      - command:
        - /bin/sh
        - -exc
        - |
          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
          if test $STATUSCODE -ne 200; then
              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
              exit 1
          fi
        name: frontend-check
        image: busybox:latest
        env:
        - name: FRONTEND_ADDR
          value: "frontend.production.svc.cluster.local:80"
      containers:
      - name: main
        image: muralidharanm/murallidharanmrepo:loadgenerator
        env:
        - name: FRONTEND_ADDR
          value: "frontend.production.svc.cluster.local:80"
        - name: USERS
          value: "10"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name: server
        image: muralidharanm/murallidharanmrepo:currencyservice
        ports:
        - name: grpc
          containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        - name: DISABLE_PROFILER
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: currency-headless
spec:
  type: Headless
  selector:
    app: currency
  ports:
  - port: 7000
    targetPort: 7000
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: server
        image: muralidharanm/murallidharanmrepo:shippingservice
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: shipping-headless
spec:
  type: Headless
  selector:
    app: shipping
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
spec:
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
spec:
  type: Headless
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: server
        image: muralidharanm/murallidharanmrepo:adservice
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
---
apiVersion: v1
kind: Service
metadata:
  name: ad-headless
spec:
  type: Headless
  selector:
    app: ad
  ports:
  - port: 9555
    targetPort: 9555
    protocol: TCP
---
